import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  ArrowUpDown,
  BatteryCharging,
  Cable,
  Car,
  CircleAlert,
  CircleDot,
  CircuitBoard,
  Cpu,
  Disc3,
  Droplet,
  Droplets,
  Fan,
  Flame,
  Folder,
  Gauge,
  GitBranch,
  HelpCircle,
  KeyRound,
  Layers,
  Lightbulb,
  ListOrdered,
  MemoryStick,
  Network,
  Plug,
  PlayCircle,
  Puzzle,
  Radio,
  Rocket,
  Route,
  ScrollText,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  Sliders,
  Snowflake,
  Sparkles,
  Stethoscope,
  Table2,
  Thermometer,
  ToggleLeft,
  TrendingUp,
  Usb,
  Waves,
  Wind,
  Wrench,
  Zap,
} from "lucide-react";
import type { SidebarNode } from "../components/tuner-ui";

/**
 * Ordered keyword -> icon rules used to pick a meaningful icon for a menu/tree
 * node based on its label. Rules are checked top-to-bottom; the first match wins,
 * so more specific patterns should come before broader ones.
 */
const KEYWORD_RULES: Array<{ test: RegExp; icon: LucideIcon }> = [
  // --- Top-level category folders --------------------------------------
  { test: /^setup$/i, icon: Wrench },
  { test: /^fuel$/i, icon: Droplet },
  { test: /^ignition$/i, icon: Flame },
  { test: /^cranking$/i, icon: PlayCircle },
  { test: /^idle$/i, icon: Wind },
  { test: /^advanced$/i, icon: Settings2 },
  { test: /^sensors?$/i, icon: Radio },
  { test: /^can\s*-?bus$/i, icon: Network },
  { test: /^controller$/i, icon: Cpu },
  { test: /^expert\s*\/?\s*extra$/i, icon: Puzzle },
  { test: /^(help|about)$/i, icon: HelpCircle },
  { test: /^diagnostics?$/i, icon: Stethoscope },
  { test: /^tools?$/i, icon: Wrench },
  { test: /^tables?$/i, icon: Table2 },
  { test: /^(curves?|graphs?)$/i, icon: TrendingUp },

  // --- Specific, well-known settings pages ------------------------------
  { test: /vehicle\s*info/i, icon: Car },
  { test: /limits?\s*(and|&)\s*protection/i, icon: ShieldAlert },
  { test: /misfire/i, icon: AlertTriangle },
  { test: /(vr\s*sensor|reluctance)/i, icon: Activity },
  { test: /odd\s*fire/i, icon: GitBranch },
  { test: /firing\s*order/i, icon: ListOrdered },
  { test: /\bcam(shaft)?\b/i, icon: Disc3 },
  { test: /\bcrank(shaft)?\b/i, icon: CircleDot },
  { test: /\btrigger\b/i, icon: Zap },
  { test: /(battery|alternator)/i, icon: BatteryCharging },
  { test: /key\s*input|immobili[sz]er/i, icon: KeyRound },
  { test: /sd\s*-?\s*card/i, icon: MemoryStick },
  { test: /(data\s*log|log(ging)?\b)/i, icon: ScrollText },
  { test: /standard\s*outputs?/i, icon: Plug },
  { test: /programmable\s*(ports?|outputs?)/i, icon: ToggleLeft },
  { test: /(fans?\s*(and|&)\s*water\s*pumps?)/i, icon: Fan },
  { test: /\bfan\b/i, icon: Fan },
  { test: /water\s*pump|\bpump\b/i, icon: Droplets },
  { test: /tach(ometer)?/i, icon: Gauge },
  { test: /speedo(meter)?/i, icon: Route },
  { test: /air\s*condition|\ba\/?c\b/i, icon: Snowflake },
  { test: /status\s*leds?|\bled\b/i, icon: Lightbulb },
  { test: /check\s*engine|\bmil\b/i, icon: CircleAlert },
  { test: /boost/i, icon: Gauge },
  { test: /injector/i, icon: Droplet },
  { test: /(afr|lambda|wideband|\bo2\b|oxygen)/i, icon: Waves },
  { test: /knock/i, icon: AlertTriangle },
  { test: /(spark|dwell|coil)/i, icon: Zap },
  { test: /throttle|\btps\b/i, icon: Gauge },
  { test: /\bmap\b|manifold\s*pressure/i, icon: Gauge },
  { test: /coolant|\bclt\b/i, icon: Thermometer },
  { test: /\biat\b|intake\s*air\s*temp/i, icon: Thermometer },
  { test: /\boil\b/i, icon: Droplet },
  { test: /warm\s*-?\s*up|\bwue\b|\base\b|cold\s*start/i, icon: Thermometer },
  { test: /accel(eration)?\s*enrich/i, icon: TrendingUp },
  { test: /launch\s*control/i, icon: Rocket },
  { test: /flat\s*shift|shift\s*(cut|light)/i, icon: ArrowUpDown },
  { test: /nitrous/i, icon: Flame },
  { test: /staging/i, icon: Layers },
  { test: /\bvvt\b|cam\s*control/i, icon: Disc3 },
  { test: /wizard/i, icon: Sparkles },
  { test: /(communications?|serial|usb)/i, icon: Usb },
  { test: /board|pinout|wiring/i, icon: CircuitBoard },
  { test: /security/i, icon: ShieldCheck },
  { test: /can\s*-?bus/i, icon: Network },
  { test: /\bcustom\b/i, icon: Sliders },
  { test: /(warning|alarm)/i, icon: AlertTriangle },
];

const DEFAULT_ICONS: Record<string, LucideIcon> = {
  folder: Folder,
  table: Table2,
  dialog: Settings2,
  dashboard: Gauge,
  log: ScrollText,
  help: HelpCircle,
};

/** Resolve a meaningful lucide icon component for a sidebar/menu tree node. */
export function resolveNodeIcon(label: string, type?: SidebarNode["type"]): LucideIcon {
  for (const rule of KEYWORD_RULES) {
    if (rule.test.test(label)) return rule.icon;
  }
  return DEFAULT_ICONS[type || "dialog"] || Cable;
}
